### ISSUE TITLE
[Feature]Allow SkipCertificateCheck

### ISSUE THREAD

**Issue by ryancbutler** [joshcorr/SecretManagement.Hashicorp.Vault.KV#29]
**Is your feature request related to a problem? Please describe.**
Vault with self-signed certificates currently won't function.

**Describe the solution you'd like**
Allow switch in secretvault config to bypass TLS checks. Can leverage the `SkipCertificateCheck` switch built into `invoke-restmethod` for 6.0 and above.

**Describe alternatives you've considered**
Tried some of the workarounds like without luck
`[System.Net.ServicePointManager]::ServerCertificateValidationCallback = { return $true }`

**Additional context**

**Comment by joshcorr** [comment]
This is a great idea. I can think of one way to implement this would be to put it as an option when the Vault is registered. The likely reason your workaround didn't work is because of the way that the module loads up in a run-space (which also makes it inherently tricky to troubleshoot). 

Would you want to give it a go on adding this feature? I can help you work on this if you aren't sure where to start.

**Comment by ryancbutler** [comment]
Sure! I could take this on.

**Comment by joshcorr** [comment]
Your Code is now out there on the gallery under [2.0.1-Preview](https://www.powershellgallery.com/packages/SecretManagement.Hashicorp.Vault.KV/2.0.1-Preview). Please close this issue if the function is working correctly for you.
